version: "3.3"

services:
  fbank.db:
    container_name: fbank.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Fbank2023"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    