name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "Fbank2023"
          ACCEPT_EULA: "Y"
          
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore backend/FBank.sln
    - name: Build
      run: dotnet build backend/FBank.sln --no-restore
    - name: Test
      env:
        ConnectionStrings__DefaultConnection: "Server=127.0.0.1,1433;TrustServerCertificate=true;Database=fbank;User Id=sa;Password=Fbank2023;"
      run: |
        export LANG=pt_BR.UTF-8
        dotnet test backend/FBank.sln --no-build --verbosity normal
